module.exports = {
  Organization: require('./Organization'),
  Employee: require('./Employee'),
  EmployeeAttendance: require('./EmployeeAttendance'),
  EmployeeDuty: require('./EmployeeDuty'),
  EmployeeTask: require('./EmployeeTask'),
  EmployeePasswordResetToken: require('./EmployeePasswordResetToken'),
  Product: require('./Product'),
  Inventory: require('./Inventory'),
  InventoryLog: require('./InventoryLog'),
  GunInfo: require('./GunInfo'),
  Sales: require('./Sales'),
  SaleHistory: require('./SaleHistory'),
  Collections: require('./Collections'),
  Customer: require('./Customer'),
  CustomerHistory: require('./CustomerHistory'),
  Expense: require('./Expense'),
  ExpenseCategory: require('./ExpenseCategory'),
  FinanceSummary: require('./FinanceSummary'),
  ProfitLoss: require('./ProfitLoss'),
  StockRegister: require('./StockRegister'),
  DensityRegister: require('./DensityRegister'),
  Document: require('./Document')
};
